meta_product_name: "SAS W&A | Valenciennes"
meta_title: "W&A Huissiers Valenciennes | Huissier de Justice Valenciennes (59 Nord)"
meta_description: "Huissier de justice Valenciennes (Nord - 59). Nos experts disposent d'une compétence locale et nationale pour vos constats."
meta_image: "waterlotlogo.png" # should exist in `app/assets/images/`
twitter_account: "@WAHuissiers"   # required for Twitter Cards
