meta_product_name: "Waterlot & Associés | Huissier de justice Valenciennes Nord (59)"
meta_title: "W&A Huissiers Valenciennes | Huissier de Justice Valenciennes Nord (59)"
meta_description: "P. DARRAS - Huissier de justice Valenciennes Nord (59) - Nos experts disposent d'une compétence locale et nationale pour vos constats - Découvrez nos services."
meta_image: "waterlotlogo.png" # should exist in `app/assets/images/`
twitter_account: "@WAHuissiers"   # required for Twitter Cards
